import { sql } from 'drizzle-orm';
import {
  check,
  index,
  integer,
  sqliteTable,
  text,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core';
import { accounts, lots, orderItems, orders } from './schema';

/** One durable attempt per order. An uncertain external request is NEVER retried by creating another invoice. */
export const paymentAttempts = sqliteTable(
  'payment_attempts',
  {
    orderId: text('order_id')
      .primaryKey()
      .references(() => orders.id),
    id: text('id').notNull(),
    method: text('method').notNull(),
    state: text('state').notNull(), // requesting | ready | attached | attention
    reference: text('reference'),
    amountCents: integer('amount_cents').notNull(),
    currency: text('currency').notNull(),
    actor: text('actor').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
    updatedAt: integer('updated_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (t) => [
    uniqueIndex('payment_attempts_id_idx').on(t.id),
    check(
      'payment_attempts_state_check',
      sql`${t.state} IN ('requesting','ready','attached','attention')`,
    ),
    check('payment_attempts_amount_check', sql`${t.amountCents} >= 0`),
  ],
);

/** A recovery code grants only one order, never all orders for a contact email or guest session. */
export const guestOrderKeys = sqliteTable('guest_order_keys', {
  orderId: text('order_id')
    .primaryKey()
    .references(() => orders.id),
  tokenHash: text('token_hash').notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp' }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp' })
    .notNull()
    .default(sql`(unixepoch())`),
});
export const guestOrderSessions = sqliteTable(
  'guest_order_sessions',
  {
    tokenHash: text('token_hash').primaryKey(),
    orderId: text('order_id')
      .notNull()
      .references(() => orders.id),
    expiresAt: integer('expires_at', { mode: 'timestamp' }).notNull(),
    createdAt: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (t) => [index('guest_order_sessions_order_idx').on(t.orderId)],
);

/** Integer micrograms for mass, containers for count. No material leaves the ledger on reservation. */
export const inventoryReservations = sqliteTable(
  'inventory_reservations',
  {
    itemId: text('item_id')
      .primaryKey()
      .references(() => orderItems.id),
    orderId: text('order_id')
      .notNull()
      .references(() => orders.id),
    lotId: text('lot_id')
      .notNull()
      .references(() => lots.id),
    units: integer('units').notNull(),
    unit: text('unit').notNull(),
    expiresAt: integer('expires_at', { mode: 'timestamp' }).notNull(),
    createdAt: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (t) => [
    index('inventory_reservations_lot_idx').on(t.lotId),
    index('inventory_reservations_order_idx').on(t.orderId),
    check('inventory_reservations_units_check', sql`${t.units} > 0`),
  ],
);

/**
 * A short-lived, server-priced checkout option. The browser submits only this
 * id; order acceptance re-checks the owner, cart, address and expiry before
 * copying shipping/tax into the immutable order record.
 */
export const checkoutQuotes = sqliteTable(
  'checkout_quotes',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id')
      .notNull()
      .references(() => accounts.id),
    cartFingerprint: text('cart_fingerprint').notNull(),
    addressFingerprint: text('address_fingerprint').notNull(),
    originId: text('origin_id').notNull().default('primary'),
    originLabel: text('origin_label').notNull().default('Primary location'),
    provider: text('provider').notNull(),
    shipmentId: text('shipment_id').notNull(),
    rateId: text('rate_id').notNull(),
    carrier: text('carrier').notNull(),
    service: text('service').notNull(),
    serviceName: text('service_name').notNull(),
    shippingCents: integer('shipping_cents').notNull(),
    taxCents: integer('tax_cents').notNull(),
    currency: text('currency').notNull().default('USD'),
    estimatedDays: integer('estimated_days'),
    test: integer('test', { mode: 'boolean' }).notNull().default(false),
    expiresAt: integer('expires_at', { mode: 'timestamp' }).notNull(),
    createdAt: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (t) => [
    index('checkout_quotes_account_idx').on(t.accountId),
    index('checkout_quotes_expiry_idx').on(t.expiresAt),
    check(
      'checkout_quotes_carrier_check',
      sql`${t.carrier} IN ('USPS','UPS','FedEx')`,
    ),
    check(
      'checkout_quotes_amount_check',
      sql`${t.shippingCents} > 0 AND ${t.taxCents} >= 0`,
    ),
  ],
);

/** Fresh packed-parcel rates generated by staff for a specific order. */
export const fulfillmentQuotes = sqliteTable(
  'fulfillment_quotes',
  {
    id: text('id').primaryKey(),
    orderId: text('order_id')
      .notNull()
      .references(() => orders.id),
    originId: text('origin_id').notNull().default('primary'),
    originLabel: text('origin_label').notNull().default('Primary location'),
    provider: text('provider').notNull(),
    shipmentId: text('shipment_id').notNull(),
    rateId: text('rate_id').notNull(),
    carrier: text('carrier').notNull(),
    service: text('service').notNull(),
    serviceName: text('service_name').notNull(),
    amountCents: integer('amount_cents').notNull(),
    currency: text('currency').notNull().default('USD'),
    estimatedDays: integer('estimated_days'),
    test: integer('test', { mode: 'boolean' }).notNull().default(false),
    expiresAt: integer('expires_at', { mode: 'timestamp' }).notNull(),
    createdBy: text('created_by').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (t) => [
    index('fulfillment_quotes_order_idx').on(t.orderId),
    check(
      'fulfillment_quotes_carrier_check',
      sql`${t.carrier} IN ('USPS','UPS','FedEx')`,
    ),
    check('fulfillment_quotes_amount_check', sql`${t.amountCents} > 0`),
  ],
);

/** One durable label-purchase claim per order prevents duplicate carrier charges. */
export const shippingLabels = sqliteTable(
  'shipping_labels',
  {
    id: text('id').primaryKey(),
    orderId: text('order_id')
      .notNull()
      .references(() => orders.id),
    quoteId: text('quote_id')
      .notNull()
      .references(() => fulfillmentQuotes.id),
    state: text('state').notNull(), // requesting | ready | voiding | attention | voided
    originId: text('origin_id').notNull().default('primary'),
    originLabel: text('origin_label').notNull().default('Primary location'),
    providerRef: text('provider_ref'),
    labelUrl: text('label_url'),
    trackingNumber: text('tracking_number'),
    carrier: text('carrier').notNull(),
    serviceName: text('service_name').notNull(),
    amountCents: integer('amount_cents').notNull(),
    test: integer('test', { mode: 'boolean' }).notNull().default(false),
    error: text('error'),
    refundState: text('refund_state'), // requesting | pending | success | attention
    refundRef: text('refund_ref'),
    refundReason: text('refund_reason'),
    refundRequestedBy: text('refund_requested_by'),
    refundRequestedAt: integer('refund_requested_at', { mode: 'timestamp' }),
    refundUpdatedAt: integer('refund_updated_at', { mode: 'timestamp' }),
    createdBy: text('created_by').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
    updatedAt: integer('updated_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (t) => [
    index('shipping_labels_order_idx').on(t.orderId),
    uniqueIndex('shipping_labels_active_order_idx')
      .on(t.orderId)
      .where(sql`${t.state} <> 'voided'`),
    check(
      'shipping_labels_state_check',
      sql`${t.state} IN ('requesting','ready','voiding','attention','voided')`,
    ),
    check(
      'shipping_labels_refund_state_check',
      sql`${t.refundState} IS NULL OR ${t.refundState} IN ('requesting','pending','success','attention')`,
    ),
    check('shipping_labels_amount_check', sql`${t.amountCents} > 0`),
  ],
);

/**
 * Carrier events received from Shippo. The provider event key is deterministic,
 * so webhook redelivery cannot repeat a business action. Raw payloads are not
 * retained: they can contain addresses and other customer data we do not need.
 */
export const shippingTrackingEvents = sqliteTable(
  'shipping_tracking_events',
  {
    id: text('id').primaryKey(),
    providerEventKey: text('provider_event_key').notNull(),
    eventName: text('event_name').notNull(),
    carrier: text('carrier').notNull(),
    trackingNumber: text('tracking_number').notNull(),
    providerStatusId: text('provider_status_id'),
    providerTransactionId: text('provider_transaction_id'),
    status: text('status').notNull(),
    statusDetail: text('status_detail'),
    statusAt: integer('status_at', { mode: 'timestamp' }),
    test: integer('test', { mode: 'boolean' }).notNull().default(false),
    verified: integer('verified', { mode: 'boolean' }).notNull().default(false),
    orderId: text('order_id').references(() => orders.id),
    /** received | verification_retry | recorded | delivered | unmatched | ignored | attention */
    outcome: text('outcome').notNull().default('received'),
    outcomeDetail: text('outcome_detail'),
    receivedAt: integer('received_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
    processedAt: integer('processed_at', { mode: 'timestamp' }),
  },
  (t) => [
    uniqueIndex('shipping_tracking_events_key_idx').on(t.providerEventKey),
    index('shipping_tracking_events_tracking_idx').on(t.trackingNumber),
    index('shipping_tracking_events_order_idx').on(t.orderId),
    index('shipping_tracking_events_outcome_idx').on(t.outcome, t.receivedAt),
    check(
      'shipping_tracking_events_outcome_check',
      sql`${t.outcome} IN ('received','verification_retry','recorded','delivered','unmatched','ignored','attention')`,
    ),
  ],
);
