/**
 * Generate drizzle/seed/catalog.sql from lib/catalog.ts.
 *
 * Every product is validated with the same rules the catalog manager form
 * applies, so the seed cannot load anything the form would refuse. Inserts
 * use INSERT OR IGNORE with deterministic ids, so re-running is safe and
 * never overwrites edits made through the manager.
 *
 *   npx tsx scripts/seed-catalog.ts
 *   npm run db:seed:local
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import {
  CHEMICAL_CLASSES,
  SEED_CLASSES,
  seedProducts,
  type Product,
} from '../lib/catalog';
import {
  DEFAULT_PRESENTATION,
  validateProductInput,
  type ProductInput,
} from '../lib/catalog-rules';

function q(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'NULL';
  return `'${value.replace(/'/g, "''")}'`;
}

function json(value: unknown): string {
  return q(JSON.stringify(value));
}

function productId(code: string): string {
  return `prd_${code.toLowerCase().replace(/[^a-z0-9]/g, '')}`;
}

function variantId(sku: string): string {
  return `var_${sku.toLowerCase().replace(/[^a-z0-9]/g, '')}`;
}

function toInput(p: Product): ProductInput {
  return {
    code: p.code,
    slug: p.slug,
    name: p.name,
    formalName: p.formalName,
    synonyms: p.synonyms,
    chemicalClass: p.chemicalClass,
    casNumber: p.casNumber,
    relatedCas: p.relatedCas ?? [],
    sequenceOneLetter: p.sequenceOneLetter,
    sequenceThreeLetter: p.sequenceThreeLetter,
    molecularFormula: p.molecularFormula,
    molecularWeight: p.molecularWeight,
    exactMass: p.exactMass,
    smiles: p.smiles,
    inchiKey: p.inchiKey,
    pubchemCid: p.pubchemCid,
    purity: p.purity,
    form: p.form,
    saltForm: p.saltForm,
    solubility: p.solubility,
    storageSolid: p.storageSolid,
    storageStock: p.storageStock,
    stability: p.stability,
    shipping: p.shipping,
    status: p.status,
    description: p.description,
    hazard: null,
  sourceNotes: p.sourceNotes,
    hasSds: p.hasSds,
    image: p.image,
    featured: p.featured,
    visibility: 'published',
    variants: p.packSizes.map((s) => ({
      quantity: s.quantity,
      presentation: DEFAULT_PRESENTATION,
    })),
  };
}

const statements: string[] = [
  '-- Generated by scripts/seed-catalog.ts. Do not edit by hand.',
];
let sortOrder = 0;

for (const product of seedProducts) {
  const result = validateProductInput(toInput(product), {
    classes: CHEMICAL_CLASSES,
  });
  if (!result.ok) {
    console.error(`Seed product ${product.code} fails catalog rules:`);
    console.error(
      JSON.stringify(
        { errors: result.errors, violations: result.violations },
        null,
        2,
      ),
    );
    process.exit(1);
  }
  const v = result.value;
  sortOrder += 10;
  const id = productId(v.code);

  statements.push(
    `INSERT OR IGNORE INTO products (id, code, slug, name, formal_name, synonyms, chemical_class, cas_number, related_cas, sequence_one_letter, sequence_three_letter, molecular_formula, molecular_weight, exact_mass, smiles, inchi_key, pubchem_cid, purity, form, salt_form, solubility, storage_solid, storage_stock, stability, shipping, status, description, source_notes, has_sds, image, featured, visibility, withdrawn_reason, sort_order, updated_by) VALUES (${[
      q(id),
      q(v.code),
      q(v.slug),
      q(v.name),
      q(v.formalName),
      json(v.synonyms),
      q(v.chemicalClass),
      q(v.casNumber),
      json(v.relatedCas),
      q(v.sequenceOneLetter),
      q(v.sequenceThreeLetter),
      q(v.molecularFormula),
      q(v.molecularWeight),
      q(v.exactMass),
      q(v.smiles),
      q(v.inchiKey),
      q(v.pubchemCid),
      q(v.purity),
      q(v.form),
      q(v.saltForm),
      json(v.solubility),
      q(v.storageSolid),
      q(v.storageStock),
      q(v.stability),
      q(v.shipping),
      q(v.status),
      q(v.description),
      json(v.sourceNotes),
      v.hasSds ? 1 : 0,
      q(v.image),
      v.featured ? 1 : 0,
      q(v.visibility),
      q(v.withdrawnReason),
      sortOrder,
      q('seed'),
    ].join(', ')});`,
  );

  v.variants.forEach((variant, index) => {
    const sku = variant.sku!;
    statements.push(
      `INSERT OR IGNORE INTO product_variants (id, product_id, sku, quantity, presentation, active, sort_order) VALUES (${[
        q(variantId(sku)),
        q(id),
        q(sku),
        q(variant.quantity),
        q(variant.presentation),
        variant.active === false ? 0 : 1,
        index * 10,
      ].join(', ')});`,
    );
  });
}

mkdirSync('drizzle/seed', { recursive: true });
writeFileSync('drizzle/seed/catalog.sql', statements.join('\n') + '\n');
console.log(
  `Wrote drizzle/seed/catalog.sql (${seedProducts.length} products, ${statements.length - 1} statements).`,
);

// Chemical classes seed — INSERT OR IGNORE so edits made in the manager are never overwritten.
{
  const rows = SEED_CLASSES.map(
    (c) =>
      `INSERT OR IGNORE INTO chemical_classes (id, name, blurb, sort_order, active, created_at, updated_at) VALUES (${q(c.id)}, ${q(c.name)}, ${q(c.blurb)}, ${c.sortOrder}, 1, unixepoch(), unixepoch());`,
  );
  writeFileSync(
    'drizzle/seed/classes.sql',
    `-- Generated by scripts/seed-catalog.ts. Do not edit.\n${rows.join('\n')}\n`,
  );
  console.log(`Wrote drizzle/seed/classes.sql (${rows.length} classes).`);
}
