/**
 * Generate drizzle/seed/catalog.sql from lib/catalog.ts.
 *
 * Every product is validated with the same rules the catalog manager form
 * applies, so the seed cannot load anything the form would refuse. Inserts
 * use INSERT OR IGNORE with deterministic ids, so re-running is safe and
 * never overwrites edits made through the manager.
 *
 *   npx tsx scripts/seed-catalog.ts
 *   npm run db:seed:local
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import {
  CHEMICAL_CLASSES,
  SEED_CLASSES,
  seedProducts,
  type Product,
} from '../lib/catalog';
import {
  DEFAULT_PRESENTATION,
  validateProductInput,
  type ProductInput,
} from '../lib/catalog-rules';

function q(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'NULL';
  return `'${value.replace(/'/g, "''")}'`;
}

function json(value: unknown): string {
  return q(JSON.stringify(value));
}

function productId(code: string): string {
  return `prd_${code.toLowerCase().replace(/[^a-z0-9]/g, '')}`;
}

function variantId(sku: string): string {
  return `var_${sku.toLowerCase().replace(/[^a-z0-9]/g, '')}`;
}

function toInput(p: Product): ProductInput {
  return {
    code: p.code,
    slug: p.slug,
    name: p.name,
    formalName: p.formalName,
    synonyms: p.synonyms,
    chemicalClass: p.chemicalClass,
    casNumber: p.casNumber,
    relatedCas: p.relatedCas ?? [],
    sequenceOneLetter: p.sequenceOneLetter,
    sequenceThreeLetter: p.sequenceThreeLetter,
    molecularFormula: p.molecularFormula,
    molecularWeight: p.molecularWeight,
    exactMass: p.exactMass,
    smiles: p.smiles,
    inchiKey: p.inchiKey,
    pubchemCid: p.pubchemCid,
    purity: p.purity,
    form: p.form,
    saltForm: p.saltForm,
    solubility: p.solubility,
    storageSolid: p.storageSolid,
    storageStock: p.storageStock,
    stability: p.stability,
    shipping: p.shipping,
    status: p.status,
    description: p.description,
    hazard: null,
  sourceNotes: p.sourceNotes,
    hasSds: p.hasSds,
    image: p.image,
    featured: p.featured,
    visibility: 'published',
    variants: p.packSizes.map((s) => ({
      quantity: s.quantity,
      presentation: DEFAULT_PRESENTATION,
    })),
  };
}

const statements: string[] = [
  '-- Generated by scripts/seed-catalog.ts. Do not edit by hand.',
];
let sortOrder = 0;

for (const product of seedProducts) {
  const result = validateProductInput(toInput(product), {
    classes: CHEMICAL_CLASSES,
  });
  if (!result.ok) {
    console.error(`Seed product ${product.code} fails catalog rules:`);
    console.error(
      JSON.stringify(
        { errors: result.errors, violations: result.violations },
        null,
        2,
      ),
    );
    process.exit(1);
  }
  const v = result.value;
  sortOrder += 10;
  const id = productId(v.code);

  statements.push(
    `INSERT OR IGNORE INTO products (id, code, slug, name, formal_name, synonyms, chemical_class, cas_number, related_cas, sequence_one_letter, sequence_three_letter, molecular_formula, molecular_weight, exact_mass, smiles, inchi_key, pubchem_cid, purity, form, salt_form, solubility, storage_solid, storage_stock, stability, shipping, status, description, source_notes, has_sds, image, featured, visibility, withdrawn_reason, sort_order, updated_by) VALUES (${[
      q(id),
      q(v.code),
      q(v.slug),
      q(v.name),
      q(v.formalName),
      json(v.synonyms),
      q(v.chemicalClass),
      q(v.casNumber),
      json(v.relatedCas),
      q(v.sequenceOneLetter),
      q(v.sequenceThreeLetter),
      q(v.molecularFormula),
      q(v.molecularWeight),
      q(v.exactMass),
      q(v.smiles),
      q(v.inchiKey),
      q(v.pubchemCid),
      q(v.purity),
      q(v.form),
      q(v.saltForm),
      json(v.solubility),
      q(v.storageSolid),
      q(v.storageStock),
      q(v.stability),
      q(v.shipping),
      q(v.status),
      q(v.description),
      json(v.sourceNotes),
      v.hasSds ? 1 : 0,
      q(v.image),
      v.featured ? 1 : 0,
      q(v.visibility),
      q(v.withdrawnReason),
      sortOrder,
      q('seed'),
    ].join(', ')});`,
  );

  v.variants.forEach((variant, index) => {
    const sku = variant.sku!;
    statements.push(
      `INSERT OR IGNORE INTO product_variants (id, product_id, sku, quantity, presentation, active, sort_order) VALUES (${[
        q(variantId(sku)),
        q(id),
        q(sku),
        q(variant.quantity),
        q(variant.presentation),
        variant.active === false ? 0 : 1,
        index * 10,
      ].join(', ')});`,
    );
  });
}

mkdirSync('drizzle/seed', { recursive: true });
writeFileSync('drizzle/seed/catalog.sql', statements.join('\n') + '\n');
console.log(
  `Wrote drizzle/seed/catalog.sql (${seedProducts.length} products, ${statements.length - 1} statements).`,
);

/**
 * This fixture is deliberately separate from catalog.sql. The shared catalog
 * seed is also used by staging and production; this row exists only to make a
 * fresh local buying-flow baseline exercise a real product route.
 */
const localBaselineSeed = [
  '-- Local-only buying-flow baseline fixture. Do not apply to staging or production.',
  `INSERT OR IGNORE INTO products (id, code, slug, name, formal_name, synonyms, chemical_class, cas_number, related_cas, sequence_one_letter, sequence_three_letter, molecular_formula, molecular_weight, exact_mass, smiles, inchi_key, pubchem_cid, purity, form, salt_form, solubility, storage_solid, storage_stock, stability, shipping, status, description, source_notes, has_sds, image, featured, visibility, withdrawn_reason, sort_order, updated_by) VALUES (${[
    q('prd_local_baseline'),
    q('NPL-999'),
    q('synthetic-baseline-material'),
    q('Synthetic Baseline Material'),
    q('Synthetic baseline reference compound'),
    json(['Local buying-flow fixture']),
    q('Peptides'),
    q('50-00-0'),
    json([]),
    'NULL',
    'NULL',
    q('C1H2'),
    q('14.03 g/mol'),
    'NULL',
    'NULL',
    'NULL',
    'NULL',
    q('≥98% by HPLC'),
    q('Solid'),
    q('Free form'),
    json([]),
    q('-20 °C'),
    q('Prepare fresh; store at -20 °C'),
    q('Local fixture'),
    q('Ambient'),
    q('available'),
    q('Synthetic reference material used only to exercise the local buying-flow baseline.'),
    json(['Local-only automated fixture; not a saleable catalog record.']),
    0,
    q('/products/synthetic-baseline-material.svg'),
    0,
    q('published'),
    'NULL',
    9990,
    q('local-baseline-fixture'),
  ].join(', ')});`,
  `INSERT OR IGNORE INTO product_variants (id, product_id, sku, quantity, presentation, list_price_cents, institutional_price_cents, price_breaks, active, sort_order) VALUES (${[
    q('var_local_baseline_5mg'),
    q('prd_local_baseline'),
    q('NPL-999-5MG'),
    q('5 mg'),
    q(DEFAULT_PRESENTATION),
    1250,
    1000,
    'NULL',
    1,
    0,
  ].join(', ')});`,
  `INSERT OR IGNORE INTO lots (id, lot_number, product_code, product_name, cas_number, manufacturer_name, manufacturer_address, received_at, purity_result, purity_method, identity_confirmed, identity_method, accession_number, analytical_lab, testing_standard, status, released_by, released_at, quantity_received, quantity_remaining, storage_condition) VALUES (${[
    q('lot_local_baseline'),
    q('LOCAL-BASELINE-2609'),
    q('NPL-999'),
    q('Synthetic Baseline Material'),
    q('50-00-0'),
    q('Synthetic Fixture Manufacturer'),
    q('1 Fixture Way, Test City'),
    "unixepoch('2026-09-01T00:00:00Z')",
    q('98.4%'),
    q('RP-HPLC'),
    1,
    q('LC-MS'),
    q('LOCAL-BASELINE-ACC-2609'),
    q('Synthetic Fixture Laboratory'),
    q('Local baseline panel v1'),
    q('released'),
    q('local-baseline-fixture'),
    "unixepoch('2026-09-01T00:00:00Z')",
    q('25 mg'),
    q('25 mg'),
    q('-20 °C'),
  ].join(', ')});`,
].join('\n');
writeFileSync('drizzle/seed/local-baseline.sql', `${localBaselineSeed}\n`);
console.log('Wrote drizzle/seed/local-baseline.sql (1 product, 1 variant, 1 released lot).');

// Chemical classes seed — INSERT OR IGNORE so edits made in the manager are never overwritten.
{
  const rows = SEED_CLASSES.map(
    (c) =>
      `INSERT OR IGNORE INTO chemical_classes (id, name, blurb, sort_order, active, created_at, updated_at) VALUES (${q(c.id)}, ${q(c.name)}, ${q(c.blurb)}, ${c.sortOrder}, 1, unixepoch(), unixepoch());`,
  );
  writeFileSync(
    'drizzle/seed/classes.sql',
    `-- Generated by scripts/seed-catalog.ts. Do not edit.\n${rows.join('\n')}\n`,
  );
  console.log(`Wrote drizzle/seed/classes.sql (${rows.length} classes).`);
}
